server:
  port: 4041

spring:
  application:
    name: JRTP701-BootJpaProj02-ReportAPI
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jrtp701db
    username: root
    password: srikanta
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never